package com.blazeloader.api.client;

import java.util.ArrayList;
import java.util.List;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;

/**
 * Utility class for making it easier to build entity models.
 */
public class ModelFactory {
	
	private List<ModelFactory> children = null;
	private List<Box> boxes = null;
	
	private boolean isInBuild = false;
	
	private ModelBase modelBase;
	
	private boolean mirror = false;
	private boolean hidden = false;
	
	private float[] offset = null;
	private float[] rotation = null;
	private float[] rotationPoint = null;
	
	private int[] texSize = null;
	private int[] texOffset = new int[2];
	
	private ModelFactory(ModelBase model) {
		modelBase = model;
	}
	
	/**
	 * Builds a model renderer based on the settings defined in this factory.
	 * <p>
	 * You would call this at the end to get back a completed ModelRenderer. 
	 */
	public ModelRenderer build() {
		if (isInBuild) throw new RuntimeException("Circular parent-child relationship detected! Can only perform one build at a time.");
		isInBuild = true;
		ModelRenderer result = new ModelRenderer(modelBase, texOffset[0], texOffset[1]);
		result.mirror = mirror;
		if (rotation != null) {
			result.rotateAngleX = rotation[0];
			result.rotateAngleY = rotation[1];
			result.rotateAngleZ = rotation[2];
		}
		if (offset != null) {
			result.offsetX = offset[0];
			result.offsetY = offset[1];
			result.offsetZ = offset[2];
		}
		if (rotationPoint != null) {
			result.setRotationPoint(rotationPoint[0], rotationPoint[1], rotationPoint[2]);
		}
		if (texSize != null) {
			result.setTextureSize(texSize[0], texSize[1]);
		}
		if (texOffset != null) {
			result.setTextureOffset(texOffset[0], texOffset[1]);
		}
		result.isHidden = hidden;
		if (boxes != null) {
			for (Box i : boxes) {
				i.build(result);
			}
		}
		if (children != null) {
			for (ModelFactory i : children) {
				result.addChild(i.build());
			}
		}
		isInBuild = false;
		return result;
	}
	
	/**
	 * Adds another ModelFactory as a child of this one.
	 * 
	 * @return Returns this model factory
	 */
	public ModelFactory append(ModelFactory other) {
		if (children == null) children = new ArrayList<ModelFactory>();
		children.add(other);
		return this;
	}
	
	/**
	 * Creates a new ModelFactory and initialises it as a child of this one
	 *  
	 * @param texOffsetX	Texture offset X
	 * @param texOffsetY	Texture offset Y
	 * @param rotX			Rotation angle X in radians
	 * @param rotY			Rotation angle Y in radians
	 * @param rotZ			Rotation angle Z in radians
	 * 
	 * @return The child ModelFactory
	 */
	public ModelFactory child(int texOffsetX, int texOffsetY, float rotX, float rotY, float rotZ) {
		ModelFactory child = ModelFactory.create(modelBase, texOffsetX, texOffsetY, rotX, rotY, rotZ);
		append(child);
		return child;
	}
	
	/**
	 * Adds a box to this ModelRactory.
	 * 
	 * @param oriX			Box origin X
	 * @param oriY			Box origin Y
	 * @param oriZ			Box origin Z
	 * @param width			Box width (z)
	 * @param height		Box height (y)
	 * @param depth			Box depth (x)
	 * @param scaleFactor	An addition scale factor to offset the size of the box. Used when scaling a model.
	 * 
	 * @return	This ModelFactory
	 */
	public ModelFactory addBox(float oriX, float oriY, float oriZ, int width, int height, int depth, float scaleFactor) {
		if (boxes == null) boxes = new ArrayList<Box>();
		boxes.add(new Box(oriX, oriY, oriZ, width, height, depth, scaleFactor));
		return this;
	}
	
	/**
	 * Marks the ModelRenderer generated by this factory to have mirrored textures.
	 * 
	 * @return	This ModelFactory 
	 */
	public ModelFactory mirror() {
		mirror = true;
		return this;
	}
	
	/**
	 * Set an offset amount.
	 * 
	 * @param x		Offset X
	 * @param y		Offset Y
	 * @param z		Offset Z
	 * 
	 * @return	This ModelFactory	
	 */
	public ModelFactory offset(float x, float y, float z) {
		if (offset == null) offset = new float[3];
    	offset[0] = x;
    	offset[1] = y;
    	offset[2] = z;
		return this;
	}
	
	/**
	 * Set rotation angles
	 * 
	 * @param x		Rotate X
	 * @param y		Rotate Y
	 * @param z		Rotate Z
	 * 
	 * @return	This ModelFactory
	 */
	public ModelFactory rotate(float x, float y, float z) {
		if (rotation == null) rotation = new float[3];
		rotation[0] = x;
		rotation[1] = y;
		rotation[2] = z;
		return this;
	}
	
	/**
	 * Set the texture offset distance. Relative to the top-left corner of the texture file.
	 * <p>
	 * Units are measured in texture units, pixel units assuming a 64x texture file.
	 * <br>
	 * x: 0 to texture width
	 * <br>
	 * y: 0 to texture-height
	 * 
	 * @param texX	Texture Offset X
	 * @param texY	Texture Offset Y
	 * 
	 * @return	This ModelFactory
	 */
	public ModelFactory setTextureOffset(int texX, int texY) {
		texOffset[0] = texX;
		texOffset[1] = texY;
		return this;
	}
	
	/**
	 * Sets the texture size for this model renderer. This is the actual size of the texture file used.
	 * <p>
	 * Units are measured in texture units, pixel units assuming a 64x texture file.
	 * 
	 * @param width		Texture Width (default: 64)
	 * @param height	Texture Height (default: 32)
	 * 
	 * @return	This ModelFactory
	 */
	public ModelFactory setTextureSize(int width, int height) {
		if (texSize == null) texSize = new int[2];
		texSize[0] = width;
		texSize[1] = height;
		return this;
	}
	
	/**
	 * Sets the rotation point for this model.
	 * 
	 * @param x		Rotation-point X
	 * @param y		Rotation-point Y
	 * @param z		Rotation-point Z
	 * 
	 * @return	This ModelFactory
	 */
	public ModelFactory setRotationPoint(float x, float y, float z) {
		if (rotationPoint == null) rotationPoint = new float[3];
		rotationPoint[0] = x;
		rotationPoint[1] = y;
		rotationPoint[2] = z;
		return this;
	}
	
	/**
	 * Sets the visibility of the model. Whether it is hidden or not.
	 */
	public void setVisibility(boolean visible) {
		hidden = !visible;
	}
	
	/**
	 * Creates a new ModelFactory and initialises it with a texture offset and rotation point.
	 * <p>
	 * After this you would call addBox to add the first cube.
	 * 
	 * @param modelBase		The ModelBase for which we are constructing cubes 
	 * @param texOffsetX	Texture Offset X
	 * @param texOffsetY	Texture Offset Y
	 * @param rotX			Rotation-point X
	 * @param rotY			Rotation-point Y
	 * @param rotZ			Rotation-point Z
	 * 
	 * @return A newly created ModelFactory
	 */
	public static ModelFactory create(ModelBase modelBase, int texOffsetX, int texOffsetY, float rotX, float rotY, float rotZ) {
		return new ModelFactory(modelBase).setTextureOffset(texOffsetX, texOffsetY).setRotationPoint(rotX, rotY, rotZ);
	}
	
	private class Box {
		float[] origin = new float[3];
		int[] size = new int[3];
		float scaleFactor = 0;
		
		Box(float oriX, float oriY, float oriZ, int width, int height, int depth, float scale) {
			origin[0] = oriX;
			origin[1] = oriY;
			origin[2] = oriZ;
			size[0] = width;
			size[1] = height;
			size[2] = depth;
			scaleFactor = scale;
		}
		
		void build(ModelRenderer renderer) {
			renderer.addBox(origin[0], origin[1], origin[2], size[0], size[1], size[2], scaleFactor);
		}
	}
}
